# Generated by Django 5.0.14 on 2026-06-27 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("case_number", models.CharField(max_length=50, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "case_type",
                    models.CharField(
                        choices=[
                            ("FRAUD_INVESTIGATION", "Fraud Investigation"),
                            ("KYC_REVIEW", "KYC Review"),
                            ("COMPLIANCE_CHECK", "Compliance Check"),
                            ("SUSPICIOUS_ACTIVITY", "Suspicious Activity"),
                            ("REGULATORY_REPORTING", "Regulatory Reporting"),
                            ("CUSTOMER_COMPLAINT", "Customer Complaint"),
                            ("INTERNAL_AUDIT", "Internal Audit"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("IN_PROGRESS", "In Progress"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("ESCALATED", "Escalated"),
                            ("RESOLVED", "Resolved"),
                            ("CLOSED", "Closed"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                (
                    "related_transaction_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "related_user_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "related_account_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("resolution", models.TextField(blank=True, null=True)),
                ("resolution_summary", models.TextField(blank=True, null=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "cases",
                "ordering": ["-opened_at"],
            },
        ),
        migrations.CreateModel(
            name="CaseComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("is_internal", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="cases.case",
                    ),
                ),
            ],
            options={
                "db_table": "case_comments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CaseDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="case_documents/")),
                ("filename", models.CharField(max_length=255)),
                ("file_size", models.PositiveIntegerField()),
                ("content_type", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="cases.case",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "case_documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(fields=["case_number"], name="cases_case_nu_25894f_idx"),
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(
                fields=["status", "priority"], name="cases_status_c72509_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(
                fields=["assigned_to", "status"], name="cases_assigne_e5cc07_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(fields=["case_type"], name="cases_case_ty_37d3f0_idx"),
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(fields=["opened_at"], name="cases_opened__770ade_idx"),
        ),
    ]
