# Generated by Django 5.0.14 on 2026-06-27 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplianceRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "regulation_type",
                    models.CharField(
                        choices=[
                            ("AML", "Anti-Money Laundering"),
                            ("KYC", "Know Your Customer"),
                            ("CTF", "Counter-Terrorism Financing"),
                            ("GDPR", "General Data Protection Regulation"),
                            ("PCI_DSS", "Payment Card Industry DSS"),
                            ("SOX", "Sarbanes-Oxley Act"),
                            ("BASEL_III", "Basel III"),
                            ("LOCAL_REGULATION", "Local Regulation"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                ("applies_to_transaction_types", models.JSONField(default=list)),
                (
                    "applies_to_amount_threshold",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("applies_to_countries", models.JSONField(default=list)),
                ("rule_config", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("effective_from", models.DateField()),
                ("effective_until", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "compliance_rules",
                "ordering": ["-severity", "code"],
            },
        ),
        migrations.CreateModel(
            name="ComplianceReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_number", models.CharField(max_length=50, unique=True)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("SAR", "Suspicious Activity Report"),
                            ("CTR", "Currency Transaction Report"),
                            ("STR", "Suspicious Transaction Report"),
                            ("PERIODIC", "Periodic Compliance Report"),
                            ("AD_HOC", "Ad Hoc Report"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("FILED", "Filed"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("data", models.JSONField(default=dict)),
                ("findings_summary", models.TextField(blank=True, null=True)),
                ("prepared_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("filed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prepared_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prepared_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "compliance_reports",
                "ordering": ["-prepared_at"],
            },
        ),
        migrations.CreateModel(
            name="ComplianceCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("user_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "account_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("COMPLIANT", "Compliant"),
                            ("NON_COMPLIANT", "Non-Compliant"),
                            ("PENDING_REVIEW", "Pending Review"),
                            ("EXEMPTED", "Exempted"),
                            ("UNDER_INVESTIGATION", "Under Investigation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("passed", models.BooleanField(default=False)),
                ("score", models.FloatField(help_text="Compliance score 0-100")),
                ("findings", models.JSONField(default=list)),
                ("recommendations", models.JSONField(default=list)),
                ("checked_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True, null=True)),
                (
                    "checked_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compliance_checks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_compliance_checks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checks",
                        to="compliance.compliancerule",
                    ),
                ),
            ],
            options={
                "db_table": "compliance_checks",
                "ordering": ["-checked_at"],
                "indexes": [
                    models.Index(
                        fields=["transaction_id"], name="compliance__transac_108f2c_idx"
                    ),
                    models.Index(
                        fields=["user_id"], name="compliance__user_id_323df8_idx"
                    ),
                    models.Index(
                        fields=["status"], name="compliance__status_2a0297_idx"
                    ),
                    models.Index(
                        fields=["rule", "status"], name="compliance__rule_id_3e4b09_idx"
                    ),
                ],
            },
        ),
    ]
