# Generated by Django 5.0.14 on 2026-06-24 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FraudAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("SUSPICIOUS_AMOUNT", "Suspicious Amount"),
                            ("UNUSUAL_PATTERN", "Unusual Pattern"),
                            ("MULTIPLE_ATTEMPTS", "Multiple Attempts"),
                            ("HIGH_RISK_LOCATION", "High Risk Location"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("IN_PROGRESS", "In Progress"),
                            ("RESOLVED", "Resolved"),
                        ],
                        default="OPEN",
                        max_length=15,
                    ),
                ),
                (
                    "probability",
                    models.FloatField(help_text="Fraud probability percentage"),
                ),
                ("details", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "fraud_alerts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="transaction",
            name="account_number",
            field=models.CharField(default="ACC-000000", max_length=50),
        ),
        migrations.AddField(
            model_name="transaction",
            name="fraud_probability",
            field=models.FloatField(
                default=0.0, help_text="Fraud probability percentage (0-100)"
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="risk_level",
            field=models.CharField(
                choices=[("LOW", "Low"), ("MEDIUM", "Medium"), ("HIGH", "High")],
                default="LOW",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                    ("FLAGGED", "Flagged"),
                    ("UNDER_REVIEW", "Under Review"),
                    ("CLEAR", "Clear"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("DEBIT", "Debit"),
                    ("CREDIT", "Credit"),
                    ("TRANSFER", "Transfer"),
                    ("PAYMENT", "Payment"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["risk_level"], name="transaction_risk_le_883d2c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["fraud_probability"], name="transaction_fraud_p_3a51e5_idx"
            ),
        ),
        migrations.AddField(
            model_name="fraudalert",
            name="transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fraud_alerts",
                to="transactions.transaction",
            ),
        ),
    ]
