# Generated by Django 5.0.14 on 2026-06-27 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0003_transaction_device_type_and_more"),
        ("transactions", "0004_alter_transaction_amount"),
    ]

    operations = []
