# Generated by Django 5.0.14 on 2026-06-27 18:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0005_merge_20260627_2236"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="transaction",
            name="transaction_fraud_p_3a51e5_idx",
        ),
        migrations.AddField(
            model_name="transaction",
            name="customer_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="kyc_status",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="device_type",
            field=models.CharField(
                choices=[
                    ("MOBILE", "Mobile"),
                    ("DESKTOP", "Desktop"),
                    ("ATM", "ATM"),
                    ("POS", "POS"),
                ],
                default="MOBILE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="risk_level",
            field=models.CharField(
                choices=[("LOW", "Low"), ("MEDIUM", "Medium"), ("HIGH", "High")],
                default="LOW",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["fraud_probability", "device_type"],
                name="transaction_fraud_p_d9c02c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["is_new_location"], name="transaction_is_new__f17e50_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["risk_score"], name="transaction_risk_sc_6893ae_idx"
            ),
        ),
    ]
