# Generated by Django 5.0.14 on 2026-06-27 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KYCProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "nationality",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "country_of_residence",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "id_document_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NATIONAL_ID", "National ID"),
                            ("PASSPORT", "Passport"),
                            ("DRIVING_LICENSE", "Driving License"),
                            ("PROOF_OF_ADDRESS", "Proof of Address"),
                            ("BANK_STATEMENT", "Bank Statement"),
                            ("UTILITY_BILL", "Utility Bill"),
                            ("TAX_CERTIFICATE", "Tax Certificate"),
                            ("BUSINESS_REGISTRATION", "Business Registration"),
                            ("SELFIE", "Selfie/Photo"),
                            ("OTHER", "Other"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "id_document_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("id_document_expiry", models.DateField(blank=True, null=True)),
                (
                    "id_document_country",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "employment_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "employer_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("occupation", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "annual_income",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("source_of_funds", models.TextField(blank=True, null=True)),
                (
                    "business_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "business_registration_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "business_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("business_address", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("IN_PROGRESS", "In Progress"),
                            ("PENDING_REVIEW", "Pending Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("EXPIRED", "Expired"),
                            ("REQUIRES_UPDATE", "Requires Update"),
                        ],
                        default="NOT_STARTED",
                        max_length=20,
                    ),
                ),
                (
                    "risk_rating",
                    models.CharField(
                        choices=[
                            ("LOW", "Low Risk"),
                            ("MEDIUM", "Medium Risk"),
                            ("HIGH", "High Risk"),
                            ("PROHIBITED", "Prohibited"),
                        ],
                        default="LOW",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_kyc_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyc_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "kyc_profiles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KYCDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("NATIONAL_ID", "National ID"),
                            ("PASSPORT", "Passport"),
                            ("DRIVING_LICENSE", "Driving License"),
                            ("PROOF_OF_ADDRESS", "Proof of Address"),
                            ("BANK_STATEMENT", "Bank Statement"),
                            ("UTILITY_BILL", "Utility Bill"),
                            ("TAX_CERTIFICATE", "Tax Certificate"),
                            ("BUSINESS_REGISTRATION", "Business Registration"),
                            ("SELFIE", "Selfie/Photo"),
                            ("OTHER", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("file", models.FileField(upload_to="kyc_documents/")),
                ("filename", models.CharField(max_length=255)),
                ("file_size", models.PositiveIntegerField()),
                ("content_type", models.CharField(max_length=100)),
                ("is_verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("verification_notes", models.TextField(blank=True, null=True)),
                ("extracted_data", models.JSONField(blank=True, default=dict)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "verified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_kyc_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "kyc_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="kyc.kycprofile",
                    ),
                ),
            ],
            options={
                "db_table": "kyc_documents",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="KYCCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "check_type",
                    models.CharField(
                        choices=[
                            ("IDENTITY", "Identity Verification"),
                            ("ADDRESS", "Address Verification"),
                            ("PEP", "PEP/Sanctions Screening"),
                            ("ADVERSE_MEDIA", "Adverse Media Check"),
                            ("DOCUMENT", "Document Verification"),
                            ("BIOMETRIC", "Biometric Verification"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PASSED", "Passed"),
                            ("FAILED", "Failed"),
                            ("MANUAL_REVIEW", "Manual Review Required"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        blank=True, help_text="Check score 0-100", null=True
                    ),
                ),
                ("details", models.JSONField(blank=True, default=dict)),
                ("provider", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "provider_reference",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_kyc_checks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "kyc_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checks",
                        to="kyc.kycprofile",
                    ),
                ),
            ],
            options={
                "db_table": "kyc_checks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="kycprofile",
            index=models.Index(
                fields=["user", "status"], name="kyc_profile_user_id_f0913d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="kycprofile",
            index=models.Index(fields=["status"], name="kyc_profile_status_ad06a5_idx"),
        ),
        migrations.AddIndex(
            model_name="kycprofile",
            index=models.Index(
                fields=["risk_rating"], name="kyc_profile_risk_ra_4b7426_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="kycprofile",
            index=models.Index(
                fields=["created_at"], name="kyc_profile_created_73c0d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="kyccheck",
            index=models.Index(
                fields=["kyc_profile", "check_type"],
                name="kyc_checks_kyc_pro_c584c7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="kyccheck",
            index=models.Index(fields=["status"], name="kyc_checks_status_3c750e_idx"),
        ),
    ]
