# Generated by Django 5.0.14 on 2026-06-27 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="refreshtoken",
            name="user",
        ),
        migrations.CreateModel(
            name="TwoFactorBackupCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10)),
                ("is_used", models.BooleanField(default=False)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backup_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "two_factor_backup_codes",
                "unique_together": {("user", "code")},
            },
        ),
        migrations.CreateModel(
            name="TwoFactorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=50)),
                (
                    "method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EMAIL", "Email"),
                            ("SMS", "SMS"),
                            ("AUTH_APP", "Authenticator App"),
                            ("BACKUP_CODE", "Backup Code"),
                            ("HARDWARE_KEY", "Hardware Key"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="two_factor_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "two_factor_logs",
            },
        ),
        migrations.CreateModel(
            name="TwoFactorSetup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "primary_method",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Email"),
                            ("SMS", "SMS"),
                            ("AUTH_APP", "Authenticator App"),
                            ("BACKUP_CODE", "Backup Code"),
                            ("HARDWARE_KEY", "Hardware Key"),
                        ],
                        default="AUTH_APP",
                        max_length=20,
                    ),
                ),
                ("backup_methods", models.JSONField(default=list)),
                ("is_enabled", models.BooleanField(default=False)),
                ("is_required", models.BooleanField(default=False)),
                ("email_verified", models.BooleanField(default=False)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("phone_verified", models.BooleanField(default=False)),
                ("secret_key", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "recovery_codes",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                (
                    "hardware_key_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="two_factor_setup",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "two_factor_setups",
            },
        ),
        migrations.CreateModel(
            name="TwoFactorToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=255)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Email"),
                            ("SMS", "SMS"),
                            ("AUTH_APP", "Authenticator App"),
                            ("BACKUP_CODE", "Backup Code"),
                            ("HARDWARE_KEY", "Hardware Key"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("device", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("is_used", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="two_factor_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "two_factor_tokens",
            },
        ),
        migrations.DeleteModel(
            name="PasswordResetToken",
        ),
        migrations.DeleteModel(
            name="RefreshToken",
        ),
        migrations.AddIndex(
            model_name="twofactorlog",
            index=models.Index(
                fields=["user", "created_at"], name="two_factor__user_id_e2e81e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="twofactorlog",
            index=models.Index(
                fields=["created_at"], name="two_factor__created_c19a4b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="twofactortoken",
            index=models.Index(
                fields=["user", "is_used"], name="two_factor__user_id_ae0256_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="twofactortoken",
            index=models.Index(
                fields=["expires_at"], name="two_factor__expires_68b774_idx"
            ),
        ),
    ]
